"""Add img column to books

Revision ID: 515a9e4c63a1
Revises: 7aec2fb36dec
Create Date: 2024-06-12 10:51:49.923974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515a9e4c63a1'
down_revision = '7aec2fb36dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
